services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    entrypoint: ["sh", "-c", "/usr/share/opensearch/init-security.sh"]
    volumes:
      - ./init-security.sh:/usr/share/opensearch/init-security.sh
      - opensearch-data1:/usr/share/opensearch/data
      - ./certificates/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certificates/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./certificates/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      - ./certificates/node1.pem:/usr/share/opensearch/config/node1.pem
      - ./certificates/node1-key.pem:/usr/share/opensearch/config/node1-key.pem
      - ./config/custom-opensearch_node_1.yml:/usr/share/opensearch/config/opensearch.yml
      - ./securityconfig:/usr/share/opensearch/plugins/opensearch-security/securityconfig
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./certificates/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certificates/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./certificates/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      - ./certificates/node2.pem:/usr/share/opensearch/config/node2.pem
      - ./certificates/node2-key.pem:/usr/share/opensearch/config/node2-key.pem
      - ./config/custom-opensearch_node_2.yml:/usr/share/opensearch/config/opensearch.yml
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net
    volumes:
      - ./config/dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ./certificates/opensearch-dashboards-key.pem:/usr/share/opensearch-dashboards/config/opensearch-dashboards-key.pem
      - ./certificates/opensearch-dashboards.pem:/usr/share/opensearch-dashboards/config/opensearch-dashboards.pem
      - ./certificates/root-ca.pem:/usr/share/opensearch-dashboards/config/root-ca.pem
      ### CHANGE TO YOUR NEEDS ###
      - ./images/GGS.png:/usr/share/opensearch-dashboards/assets/GGS.png
      - ./images/GGS-logo.png:/usr/share/opensearch-dashboards/assets/GGS-logo.png
      - ./images/GGS-light.png:/usr/share/opensearch-dashboards/assets/GGS-light.png
      - ./images/GGS-logo-light.png:/usr/share/opensearch-dashboards/assets/GGS-logo-light.png

  nginx:
    image: nginx:latest
    container_name: opensearch-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates/nginx.pem:/etc/nginx/certs/nginx.pem
      - ./certificates/nginx-key.pem:/etc/nginx/certs/nginx-key.pem
      - ./certificates/root-ca.pem:/etc/nginx/certs/root-ca.pem
    networks:
      - opensearch-net

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
      - WEBPASSWORD=admin  # Set this to access the admin panel
      - PIHOLE_DOCKER_TAG=latest
    ports:
      - "8080:80"  # Mapping port 8080 to Pi-hole's port 80
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./pihole/etc-pihole/:/etc/pihole/"
      - "./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    networks:
      - opensearch-net


volumes:
  opensearch-data1:
  opensearch-data2:
  pihole_data:
  dnsmasq_data:
  
networks:
  opensearch-net:
